drop database yjstest;
create database yjstest default character set utf8;
use yjstest;
create table goods(
id integer auto_increment primary key,
type_1 varchar(1000),
type_2 varchar(50),
type_3 varchar(50),
type_4 varchar(50),
type_search varchar(50),
sptp varchar(255),
plsl varchar(255),
dpmc varchar(50),
sptb varchar(255),
innerUrl varchar(50),
spjg varchar(50),
pinpai varchar(50),
spmc varchar(255),
spbh varchar(1000),
huohao varchar(50),
dianpu varchar(500),
spmz varchar(50),
spcd varchar(50),
gcjk varchar(50),
dianyuan varchar(50),
fenlei varchar(50),
leibie varchar(50),
tese varchar(50),
texing varchar(50),
jiawei varchar(50),
guige varchar(50),
chicun varchar(255),
yuanliao varchar(50),
shuliang varchar(50),
yongtu varchar(50),
xingzhi varchar(50),
chima varchar(50),
qunchang varchar(50),
mianliao varchar(50),
houdu varchar(50),
lingxiang varchar(50),
lxys varchar(50),
syjj varchar(50),
sfyd varchar(50),
sycj varchar(50),
syrq varchar(50),
fzs varchar(50),
dmfs varchar(50),
jygn varchar(50),
clbw varchar(50),
znbj varchar(50),
cdfs varchar(50),
ylfw varchar(50),
gzms varchar(50),
ylms varchar(50),
zhongliang varchar(50),
sybw varchar(50),
dyfs varchar(50),
syzt varchar(255),
baozhuang varchar(255),
lmbs varchar(50),
kuanshi varchar(50),
sfkwc varchar(50),
xingtai varchar(50),
xingzhuang varchar(50),
syfs varchar(50),
fengge varchar(50),
caizhi varchar(50),
xiuchang varchar(50),
sydx varchar(50),
xgrd varchar(50),
sylx varchar(50),
ypjx varchar(50),
syff varchar(50),
zycf varchar(50),
gongxiao varchar(50),
gongneng varchar(255),
kzlx varchar(50),
spsp varchar(255),
ylqxzczbh varchar(50),
ylqxmc varchar(10000),
xinghao varchar(255),
zcrhzbarxx varchar(50),
scqy varchar(50),
scxkzhbapzbh varchar(50),
gxyjs varchar(50),
yybb varchar(50),
jyfs varchar(50),
jygnc varchar(50),
clfw varchar(50),
sfzdgb varchar(50),
clff varchar(50),
clsj varchar(50),
cljd varchar(50),
cpcc varchar(50),
xsfs varchar(50),
jgjzc varchar(50),
syfw varchar(50),
tqms varchar(50),
yqnd varchar(50),
yqll varchar(50),
gonglv varchar(50),
whklsfkt varchar(50),
whlsfkt varchar(50),
jjz varchar(50),
zctj varchar(50),
ysjsm varchar(50),
whkldxfb varchar(50),
rongliang varchar(50),
gdgzms varchar(50),
zlbcc varchar(50),
cpjz varchar(50),
zdzz varchar(50),
zuokuan varchar(50),
zdh varchar(50),
lcc varchar(50),
ltlx varchar(50),
zxzwbj varchar(50),
ppds varchar(50),
dclx varchar(50),
dcrl varchar(50),
llcdsj varchar(50),
zdsl varchar(50),
edxh varchar(50),
ypspm varchar(50),
yptym varchar(50),
pzwh varchar(50),
cpgg varchar(50),
yfyl varchar(50),
yxq varchar(50),
syzgnzz varchar(50),
bzgg varchar(50),
knsfaphgl varchar(50),
knsfagysgl varchar(50),
blfy varchar(50),
bzq varchar(50),
gongyong varchar(255),
synl varchar(50),
spxqtp text
)DEFAULT CHARSET=utf8;

#插入数据
insert into goods (type_1,type_2,type_3,type_4,type_search,sptp,plsl,dpmc,sptb,innerUrl,spjg,pinpai,spmc,spbh,huohao,dianpu,spmz,spcd,gcjk,dianyuan,fenlei,leibie,tese,texing,jiawei,guige,chicun,yuanliao,shuliang,yongtu,xingzhi,chima,qunchang,mianliao,houdu,lingxiang,lxys,syjj,sfyd,sycj,syrq,fzs,dmfs,jygn,clbw,znbj,cdfs,ylfw,gzms,ylms,zhongliang,sybw,dyfs,syzt,baozhuang,lmbs,kuanshi,sfkwc,xingtai,xingzhuang,syfs,fengge,caizhi,xiuchang,sydx,xgrd,sylx,ypjx,syff,zycf,gongxiao,gongneng,kzlx,spsp,ylqxzczbh,ylqxmc,xinghao,zcrhzbarxx,scqy,scxkzhbapzbh,gxyjs,yybb,jyfs,jygnc,clfw,sfzdgb,clff,clsj,cljd,cpcc,xsfs,jgjzc,syfw,tqms,yqnd,yqll,gonglv,whklsfkt,whlsfkt,jjz,zctj,ysjsm,whkldxfb,rongliang,gdgzms,zlbcc,cpjz,zdzz,zuokuan,zdh,lcc,ltlx,zxzwbj,ppds,dclx,dcrl,llcdsj,zdsl,edxh,ypspm,yptym,pzwh,cpgg,yfyl,yxq,syzgnzz,bzgg,knsfaphgl,knsfagysgl,blfy,bzq,gongyong,synl,spxqtp) value

#查询数据
select count(distinct innerUrl) from goods;
select count(innerUrl) from goods;
select spmc,innerUrl from goods group by innerUrl having count(id) > 1 order by innerUrl;
select spmc,innerUrl from goods group by innerUrl order by innerUrl;
select count(innerUrl) from goods group by innerUrl order by count(innerUrl);

#修改表结构
alter table goods change syzt syzt varchar(500);

#删除表
delete from goods;
