# Generated by Django 2.2.2 on 2019-06-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(db_column='商品图片', max_length=100)),
                ('commodityName', models.CharField(db_column='商品名字', max_length=100)),
                ('commodityAttr', models.CharField(db_column='商品属性', max_length=100)),
                ('price', models.FloatField(db_column='商品价格')),
                ('discount', models.FloatField(db_column='商品折扣')),
                ('originalPrice', models.FloatField(db_column='商品原价')),
                ('advantage', models.CharField(db_column='商品优势', max_length=20)),
                ('policy', models.CharField(db_column='商品政策', max_length=20)),
                ('isDelete', models.BooleanField(db_column='是否删除', default=False)),
                ('lastTime', models.DateTimeField(auto_now=True, db_column='修改时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, db_column='创建时间')),
            ],
            options={
                'db_table': 'Commodity',
                'ordering': ['id'],
            },
        ),
    ]
